name: API Automation Testing

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        env: 
          AUTH_USERNAME: ${{ secrets.POSTMAN_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.POSTMAN_PASSWORD }}
        run: |
          newman run Restful-Booker.postman_collection.json \
          -e Restful-Booker.postman_environment.json \
          --env-var "username=$AUTH_USERNAME" \
          --env-var "password=$AUTH_PASSWORD"